### PR TITLE
Unfork/Update JSQMessagesViewController

### PR DESCRIPTION
**Pull request by michaelkirk**
## Description
Getting back on upstream JSQMessagesViewController fixes a couple bugs (see ##Bugfixes), and makes future upgrades easier.

The unforking process was basically this:

* Starting from  our fork: https://github.com/WhisperSystems/JSQMessagesViewController
* move custom message types (Calls and DisplayedMessages) classes from our
  custom JSQMVC fork into Signal-iOS.
* Move any method customization into our subclass. Including
  CollectionView protocol stuff, styling, bubble sizing, and gesture behavior

## BugFixes

FIXES: https://github.com/WhisperSystems/Signal-iOS/issues/1111 - incorrectly sized bubbles for incoming attachments: 
FIXES: Bubble-size re-flow when first loading thread.
FIXES: #1062?

Maybe Fixes: https://github.com/WhisperSystems/Signal-iOS/issues/838 - Rendering Glitches
Maybe Fixes: https://github.com/WhisperSystems/Signal-iOS/issues/1181 - JumbledBubbles

Also, by getting back on upstream we pave the way for #792 and generally make keeping up-to-date easier. 

This required a lot of changes. Code review appreciated. ❤️

### CODE REVIEW

**Comment by 2-4601** [comment]
Probably also fixes #1062?

**Comment by Aureleme** [comment]
Hi, 
Will you implement the JSQMessagesViewController's next update (8.0) when it will be release?

**Comment by michaelkirk** [comment]
@Aureleme - That's the plan at this point, but *when* it happens depends on how many breaking changes are incorporated in the upstream release. 

It looks like some good (and [ambitious](https://github.com/jessesquires/JSQMessagesViewController/milestone/7)) work is happening up there. 

❤️  /cc @jessesquires

**Comment by jessesquires** [comment]
See: https://github.com/jessesquires/JSQMessagesViewController/issues/1216 for more details.

Also, I would be more than happy to help Signal-iOS with the migration to `v8.0`. 😊

**Pull request merged**
