### PR TITLE
CocoaPods 1.0 update and Travis-CI compatibility

### PR DESCRIPTION
**Pull request by nicholas-lonsinger**
### First time contributor checklist

- [x] I have read the [README](https://github.com/WhisperSystems/Signal-iOS/blob/master/README.md) and [CONTRIBUTING](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md) documents
- [x] I have signed the [Contributor Licence Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I'm following the [code, UI and style conventions](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md#code-conventions)
- [x] My commits are rebased on the latest master branch
- [x] My commits are in nice logical chunks
- [x] My contribution is fully baked and is ready to be merged as is
- [x] I have tested my contribution on these devices:
 * n/a - no code changes, only pods and ci
- [x] I have made the choice whether I want the [BitHub reward](https://github.com/WhisperSystems/Signal-Android/wiki/BitHub-Rewards) or not by omitting or adding the word `FREEBIE` in my commit message

- - - - - - - - - -

### Description

* CocoaPods 1.0 compatibility. Thanks to @brianherman and @orta for the Podfile changes, taken from PR #1156
* Modified Travis-CI to use the newer CocoaPods 1.0 as well.
* Performance improvements to Travis-CI to reduce build time by 50%-75%

### CODE REVIEW

**Comment by orta** [comment]
👍

**Comment by lazerwalker** [comment]
Any chance this can get merged in? I'm trying to set up an initial dev environment, but trying to `pod install` on master is failing due to breaking CocoaPods 1.0 changes that this PR accommodates.

**Comment by michaelkirk** [comment]
If you can get this up to date with master, I'll merge it straight away. 

Bonus points if you use cocoapods 1.0.1

Thanks!

**Comment by nicholas-lonsinger** [comment]
Will do, I'll get this ready shortly.

**Comment by lazerwalker** [comment]
FYI, there shouldn't be anything needed for CocoaPods 1.0.1 support. Neither the Podfile nor the Podfile.lock mentions the cocoapod gem version, and since it's a minor release there won't be any breaking changes from 1.0.

**Comment by michaelkirk** [comment]
Closed with https://github.com/WhisperSystems/Signal-iOS/commit/e7f3092f008993ec2f18739b8047dd378a43a229.

@nicholas-lonsinger I currently am only authorized to do squash commits, so I ended up stealing your commit credit and BTC. If you send me an address I'll forward the reward your way ($72.93USD), otherwise I will return it to OWS.

**Pull request closed without merging**
