### PR TITLE
Enable action buttons for default notification context / Apple Watch support

### PR DESCRIPTION
**Pull request by neffs**
Enables replying to messages directly from apple watch.
Should bring #774 forward.

### CODE REVIEW

**Comment by neffs** [comment]
@FredericJacobs @michaelkirk Anything I can do to get this changed or merged?

**Comment by thomersch** [comment]
Can we make this thing happen? It is literally one line.

**Comment by CodeMichael** [comment]
Any chance this could get reviewed, would love to have the functionality.

**Comment by schmeat** [comment]
This has been up for over a year without a comment from the devs. 

At least we learned not to waste time contributing to this project.

**Comment by neffs** [comment]
I thought about writing some code for the watch, but I'm not sure now...

This patch is sooo simple and I don't understand why they don't just merge it or fix it themselves without telling anyone. Would love to reply with 👍 from the watch...

**Comment by v1nsai** [comment]
Was going to try pulling and patching myself, glad I checked github first. Shame that we're sitting on a solution and just waiting on someone to allow it.

Open Whisper? You guys still alive?

**Comment by v1nsai** [comment]
It looks like Actionable Notifications are already being used in the master branch, which means we should be seeing it on the Watch if I'm understanding correctly.  Gonna dig some more later.

**Comment by neffs** [comment]
@v1nsai They have been using them for a long time, but the Apple Watch picks them up only if they are defined for the default notification type (=popup window). Signal uses them only for the minimal notification (=top of screen slider).

**Comment by unconfigured** [comment]
I'm watching this issue for a long time now. My hope that this patch will be merged or watch support will be improved is nearly gone...
If someone could at least comment on what can be done to get it merged or why this issue gets stuck!?

**Comment by CodeMichael** [comment]
I believe this can be closed, as notification actions appear to have been enabled on a recent build.

**Comment by Shanesan** [comment]
Yes, great work! Seems to function with all the iOS and WatchOS standards.

**Pull request closed without merging**
