### PR TITLE
group messaging ack

### PR DESCRIPTION
**Pull request by corbett**
• DO NOT MERGE
• this is only a sketch of what would need to be changed to ack only in the following situations:
-not a group message
-Is a group update message
-I have heard about the group (i.e. previously have received an update message about it and haven't left it)
• we can see that the code is quite ugly. we have to go all the way through encryption prior to the ack. I think independent of security issues this approach is not clean
• this is just meant to be a point for discussions. if we end up going this route I will revisit this branch. also untested just a sketch.

### CODE REVIEW

**Comment by FredericJacobs** [comment]
I'll leave the last word to @moxie0 (See discussion in https://github.com/WhisperSystems/Signal-iOS/pull/248) but I don't think that this is the right way to go.

**Comment by corbett** [comment]
cool, yea me neither if there is another way. just wanted to flesh out the code changes necessary for this way. I will write a message to Moxie cc you and write the droids/bros as needed.

**Comment by FredericJacobs** [comment]
@corbett: I think this can be closed, right?

**Comment by corbett** [comment]
yes

On Sat, Jan 3, 2015 at 1:10 PM, Frederic Jacobs <notifications@github.com>
wrote:

> @corbett <https://github.com/corbett>: I think this can be closed, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/pull/258#issuecomment-68594457>
> .
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Pull request closed without merging**
