### PR TITLE
Swipe image attachments

### PR DESCRIPTION
**Pull request by danielschonfeld**
This PR addresses issue #759.  I am brand new to this and i'm sure it could use some more love...

I also seem to have a bug where the UIScrollView inset doesn't seem to take effect on initial load, i'd love if someone else could take a look at it and tell me what they think and i'd appreciate any help someone could give me to get this up to snuff in terms of merge readiness.

cc @FredericJacobs

### CODE REVIEW

**Comment by danielschonfeld** [comment]
I'm guessing someone needs to do 'pod install' ?

**Comment by FredericJacobs** [comment]
@danielschonfeld : Are you still working on this? What's the status exactly?

**Comment by danielschonfeld** [comment]
It's working but has a bug that places it on initial load at position 0,0
and I'd love some help trying to figure it out.

**Comment by danielschonfeld** [comment]
@FredericJacobs also if you have any comments, code guidelines that i didn't follow or any other suggestions to bring it up to par with your project standards, i'd be happy to work on it more so that it's merge-ready

**Comment by FredericJacobs** [comment]
@danielschonfeld : Great. I'll look into that early next week.

**Comment by danielschonfeld** [comment]
@FredericJacobs did you happen to have a chance looking at this PR? i'd love to hear some feedback

**Comment by michaelkirk** [comment]
Hi @danielschonfeld. It's been a while. =)

Are you still interested in getting this merged? Unsurprisingly it has accrued some conflicts in the last 18 months.

I'm going to close it for now, but if would be happy if you re-opened.

**Pull request closed without merging**
