### PR TITLE
More performant unread indicator search

### PR DESCRIPTION
**Pull request by michaelkirk**
It occurred to me there was a better way to do this lookup - but I couldn't reproduce the code path.

When does this code get executed @charlesmchen?

### CODE REVIEW

**Comment by charlesmchen** [comment]
Just search for `indexPathOfUnreadMessagesIndicator`.  It's used in `scrollToDefaultPosition` and `scrollToUnreadIndicatorAnimated`.

**Comment by michaelkirk** [comment]
> Just search for indexPathOfUnreadMessagesIndicator. It's used in scrollToDefaultPosition and scrollToUnreadIndicatorAnimated.

Sorry - I should have been clearer. I am aware of when this method is called, but in my testing it always hit the early return before getting to the code in this diff, seemingly even when there was an unreadIndicator. I'll try to reproduce.

**Comment by charlesmchen** [comment]
> Sorry - I should have been clearer. I am aware of when this method is called, but in my testing it always hit the early return before getting to the code in this diff, seemingly even when there was an unreadIndicator. I'll try to reproduce.

Well that ain't great.  That "early exit" check I recently added may have a bug.

**Comment by charlesmchen** [comment]
> Well that ain't great. That "early exit" check I recently added may have a bug.

@michaelkirk this works fine for me.  I just passed the early exit in group and 1:1 conversations with unread messages.

**Pull request closed without merging**
