### PR TITLE
default avatar has initials

### PR DESCRIPTION
**Pull request by corbett**
this now makes the default avatar have initials. We'll tweak fonts/colors based on @abolishme but looks good in current design.

### CODE REVIEW

**Comment by corbett** [comment]
review @FredericJacobs ?

**Comment by FredericJacobs** [comment]
I'll review everything pending tomorrow morning. Too busy with other stuff tonight!

**Comment by corbett** [comment]
np not high priority

On Thu, Jan 15, 2015 at 8:30 AM, Frederic Jacobs <notifications@github.com>
wrote:

> I'll review everything pending tomorrow morning. Too busy with other stuff
> tonight!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/pull/339#issuecomment-70135684>
> .
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by FredericJacobs** [comment]
That will require some styling but it works :+1:

**Comment by corbett** [comment]
Yea every detail in the app is being styled so we'll get there

**Pull request closed without merging**
