### PR TITLE
Charlesmchen/unread changes

### PR DESCRIPTION
**Pull request by charlesmchen**
### This PR is now ready for review.

PTAL @michaelkirk

### CODE REVIEW

**Comment by michaelkirk** [comment]
Generally speaking it's hard to review PR's based on other PR's. So I can wait until the prior is merged, *or* if you squash all the relevant commits of the feature into a single commit, I can just review/comment on that commit so we don't have the hold up.

Whichever way you prefer.

**Comment by charlesmchen** [comment]
> Generally speaking it's hard to review PR's based on other PR's. So I can wait until the prior is merged, or if you squash all the relevant commits of the feature into a single commit, I can just review/comment on that commit so we don't have the hold up.

Whenever I open a PR with a comment that says "This PR depends on X", I'm letting you know that you probably don't want to review it until X is merged.  Sorry for the confusion.

**Comment by charlesmchen** [comment]
### This PR is now ready for review.

PTAL @michaelkirk 

* f0132a5 has the bulk of the changes, which is a "straight move", decomposing the classes in MessagesViewController into multiple source files.
* 3b17ec0 has a minor change - reducing the frequency of the "mark as read" timer.  I'll probably reduce it even further, now that scrolling can also trigger the "mark as read" logic.
* 3199b58 Fixes a small glitch in the "mark as read" logic.
* 70f72b9 Only show unread indicator if there is more than one message in the thread.

**Comment by michaelkirk** [comment]
LGTM, thanks for removing a cool 1k lines from the messages view controller file.

**Pull request merged**
