### PR TITLE
Feature/better push notification messages

### PR DESCRIPTION
**Pull request by lordmortis**
Okay, i've done them against your current master as I couldn't find notificationsAdvanced :/ 

Let me know what you think (or let me know what branch to rebase it off)

Here's how it looks (I built a small tester with the same code) 

Notifications View (I can't get rid of that duplicated line sadly :/)
screen shot 2015-06-08 at 10 20 47 pm

No details at all
screen shot 2015-06-08 at 10 20 39 pm

user message - only names
screen shot 2015-06-08 at 10 20 33 pm

group message - only names
screen shot 2015-06-08 at 10 20 29 pm

User message - all details
screen shot 2015-06-08 at 10 20 23 pm

Group message - all details
screen shot 2015-06-08 at 10 20 18 pm

### CODE REVIEW

**Comment by FredericJacobs** [comment]
How are those displayed on the lockscreen?

**Comment by lordmortis** [comment]
Like this
screen shot 2015-06-09 at 3 16 14 pm

And here's how it looks on a Pebble (hopefully similar on apple watch)
img_1729

**Comment by FredericJacobs** [comment]
Lost in rebases

**Comment by lordmortis** [comment]
Would you like me to modify the new code base with these changes?

**Comment by FredericJacobs** [comment]
@lordmortis : I'm unclear about the advantages it brings compared to the current notification layout.

**Pull request closed without merging**
