### PR TITLE
#1076 - OpenSSL updated to 1.0.206.

### PR DESCRIPTION
**Pull request by ArkadiuszBanas**
It's fix for error during pod install.

FREEBIE

### CODE REVIEW

**Comment by michaelkirk** [comment]
:+1:

**Comment by nivl4** [comment]
Before this is merged, running `pod update OpenSSL` should fix it too. see [pod install vs. pod update](https://guides.cocoapods.org/using/pod-install-vs-update.html)

**Comment by michaelkirk** [comment]
It's kind of unfortunate that all PR's are failing builds until this is merged. 

Should be safe, [considering the source](https://cocoapods.org/pods/OpenSSL) of the release.

/cc @FredericJacobs

**Comment by nivl4** [comment]
@ArkadiuszBanas Would  it be possible that the `cla-server/validation` is not green because you haven't signed the [Contributor agreement](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md#contributor-agreement)?

**Comment by kompozer** [comment]
Same here, `1.0.205` doesn't work
```shell
~ » wget https://openssl.org/source/openssl-1.0.2e.tar.gz
--2016-02-29 10:22:37--  https://openssl.org/source/openssl-1.0.2e.tar.gz
...
HTTP request sent, awaiting response... 404 Not Found
2016-02-29 10:22:37 ERROR 404: Not Found.
```
`1.0.206` works just fine

**Comment by jschneier** [comment]
Sorry I didn't see this! Turns out OpenSSL was bumped again and I opened a new PR #1098

**Pull request closed without merging**
