### PR TITLE
Prevent skewed group image (#756)

### LINKED ISSUE #756: Photos selected for group conversation are skewed
When you set a photo for a group conversation, the photo is skewed. This is particularly visible when you use a 'landscape' photo. I guess that the size of the photos doesn't fit in the square/circle?

Suggestion: use a square/circle to select the area of the photo the user selects as the area to be used for the group photo. Ideally, it would also be possible to zoom in/out of the photo.

### PR DESCRIPTION
**Pull request by big-r81**
### Contributor checklist

- [x] I'm following the [code, UI and style conventions](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md#code-conventions)
- [x] My commits are rebased on the latest master branch
- [x] My commits are in nice logical chunks
- [x] My contribution is fully baked and is ready to be merged as is
- [x] I have tested my contribution on these devices:
 * iPhone 6, iOS 9.3.1
- [x] I have made the choice whether I want the [BitHub reward](https://github.com/WhisperSystems/Signal-Android/wiki/BitHub-Rewards) or not by omitting or adding the word `FREEBIE` in my commit message

- - - - - - - - - -

### Description

- fixes #756

//FREEBIE

### CODE REVIEW

**Comment by michaelkirk** [comment]
Can I get a screenshot of the group dialog and the inbox view with an easy-to-tell-if-distorted image like a square or circle?

**Comment by big-r81** [comment]
Here it is:

Group Photo

**Comment by michaelkirk** [comment]
and the inbox view?

**Comment by big-r81** [comment]
okay, this isn't working. i will investigate this...

Inbox View

**Comment by big-r81** [comment]
The inbox view:

Inbox view

**Comment by michaelkirk** [comment]
Great - thank You!

**Pull request merged**
