### PR TITLE
AppIcon: shift speech bubble up to improve visual alignment

### PR DESCRIPTION
**Pull request by dunn**
The oval part of the speech bubble was vertically centered, but the hanging triangle made it appear to be lower-than-center.  This pushes the entire bubble up to correct for that.

(If this is a welcome change let me know and I'll sign the CLA.)

### CODE REVIEW

**Comment by FredericJacobs** [comment]
Hey @abolishme,
Can you review this PR?

**Comment by FredericJacobs** [comment]
@abolishme : Can you comment on this?

**Comment by abolishme** [comment]
@FredericJacobs seems legit.

**Comment by FredericJacobs** [comment]
@abolishme I will consider this as a go ahead for a merge

**Comment by dunn** [comment]
Signed the CLA!

**Comment by FredericJacobs** [comment]
Merged as d347df9a46b8537d053bddababb5b23f496a0d36

**Pull request closed without merging**
