### PR TITLE
Fix for issue #277.

### PR DESCRIPTION
**Pull request by jackflips**
Fixed speakerphone [bug](https://github.com/WhisperSystems/Signal-iOS/issues/277). Still needs to be tested.

### CODE REVIEW

**Comment by corbett** [comment]
am testing this and will comment here (or discuss in person) as to result.
@fredericjacobs can wan't for review until that point.

On Sun, Jan 18, 2015 at 11:51 AM, Jack Rogers <notifications@github.com>
wrote:

> Fixed speakerphone bug
> <https://github.com/WhisperSystems/Signal-iOS/issues/277>. Still needs to
> be tested.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/WhisperSystems/Signal-iOS/pull/388
> Commit Summary
>
>    - issue 277, fixed speakerphone bug FREEBIE
>
> File Changes
>
>    - *M* Signal/src/audio/AppAudioManager.h
>    <https://github.com/WhisperSystems/Signal-iOS/pull/388/files#diff-0>
>    (5)
>    - *M* Signal/src/audio/AppAudioManager.m
>    <https://github.com/WhisperSystems/Signal-iOS/pull/388/files#diff-1>
>    (4)
>    - *M* Signal/src/audio/incall_audio/RemoteIOAudio.m
>    <https://github.com/WhisperSystems/Signal-iOS/pull/388/files#diff-2>
>    (5)
>
> Patch Links:
>
>    - https://github.com/WhisperSystems/Signal-iOS/pull/388.patch
>    - https://github.com/WhisperSystems/Signal-iOS/pull/388.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/pull/388>.
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by corbett** [comment]
*wait

On Sun, Jan 18, 2015 at 11:54 AM, Christine Corbett Moran <
christine.corbett@gmail.com> wrote:

> am testing this and will comment here (or discuss in person) as to result.
> @fredericjacobs can wan't for review until that point.
>
> On Sun, Jan 18, 2015 at 11:51 AM, Jack Rogers <notifications@github.com>
> wrote:
>
>> Fixed speakerphone bug
>> <https://github.com/WhisperSystems/Signal-iOS/issues/277>. Still needs
>> to be tested.
>> ------------------------------
>> You can view, comment on, or merge this pull request online at:
>>
>>   https://github.com/WhisperSystems/Signal-iOS/pull/388
>> Commit Summary
>>
>>    - issue 277, fixed speakerphone bug FREEBIE
>>
>> File Changes
>>
>>    - *M* Signal/src/audio/AppAudioManager.h
>>    <https://github.com/WhisperSystems/Signal-iOS/pull/388/files#diff-0>
>>    (5)
>>    - *M* Signal/src/audio/AppAudioManager.m
>>    <https://github.com/WhisperSystems/Signal-iOS/pull/388/files#diff-1>
>>    (4)
>>    - *M* Signal/src/audio/incall_audio/RemoteIOAudio.m
>>    <https://github.com/WhisperSystems/Signal-iOS/pull/388/files#diff-2>
>>    (5)
>>
>> Patch Links:
>>
>>    - https://github.com/WhisperSystems/Signal-iOS/pull/388.patch
>>    - https://github.com/WhisperSystems/Signal-iOS/pull/388.diff
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/WhisperSystems/Signal-iOS/pull/388>.
>>
>
>
>
> --
> Dr. Corbett Moran
> Rockets @ http://www.spacex.com
> Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
> Dev @ http://circleof6app.com
> Dev @ https://whispersystems.org
> www.christinecorbettmoran.com
>
>


-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by FredericJacobs** [comment]
Alright, I'll let you go ahead (although my impatience led me to already look over it ;) )

**Comment by corbett** [comment]
wait if you already reviewed this go for it... since he didn't test at all
on device I was trying to save you work (we had lunch though)

On Sun, Jan 18, 2015 at 11:57 AM, Frederic Jacobs <notifications@github.com>
wrote:

> Alright, I'll let you go ahead (although my impatience led me to already
> look over it ;) )
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/pull/388#issuecomment-70428189>
> .
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by corbett** [comment]
tested this on device that part looks good to me! @FredericJacobs could you do the final code review?

**Comment by FredericJacobs** [comment]
Merged as 84dbc6a45b5cf1b4728a90e9551ec43abe22e2d8

**Pull request closed without merging**
