### PR TITLE
Updated Design

### PR DESCRIPTION
**Pull request by helveticade**

### CODE REVIEW

**Comment by corbett** [comment]
@fredericjacobs can you rebase this for master so that I have more icons?

On Mon, Jan 26, 2015 at 3:48 PM, Cade <notifications@github.com> wrote:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/WhisperSystems/Signal-iOS/pull/517
> Commit Summary
>
>    - New iconography
>    - Replaced the active tab icons
>    - Updated icons #503
>
> File Changes
>
>    - *M*
>    Signal/Images.xcassets/archive-active@1x.imageset/tabArchive--active.pdf
>    <https://github.com/WhisperSystems/Signal-iOS/pull/517/files#diff-0>
>    (0)
>    - *M*
>    Signal/Images.xcassets/archive-inactive@1x.imageset/tabArchive--inactive.pdf
>    <https://github.com/WhisperSystems/Signal-iOS/pull/517/files#diff-1>
>    (0)
>    - *A* Signal/Images.xcassets/bgOWSOnboarding.imageset/Contents.json
>    <https://github.com/WhisperSystems/Signal-iOS/pull/517/files#diff-2>
>    (12)
>    - *A*
>    Signal/Images.xcassets/bgOWSOnboarding.imageset/bgOWSOnboarding.pdf
>    <https://github.com/WhisperSystems/Signal-iOS/pull/517/files#diff-3>
>    (0)
>    - *M*
>    Signal/Images.xcassets/inbox-active@1x.imageset/tabInbox--active.pdf
>    <https://github.com/WhisperSystems/Signal-iOS/pull/517/files#diff-4>
>    (0)
>    - *M*
>    Signal/Images.xcassets/inbox-inactive@1x.imageset/tabInbox--inactive.pdf
>    <https://github.com/WhisperSystems/Signal-iOS/pull/517/files#diff-5>
>    (0)
>    - *A* Signal/Images.xcassets/logoSignal.imageset/Contents.json
>    <https://github.com/WhisperSystems/Signal-iOS/pull/517/files#diff-6>
>    (12)
>    - *A* Signal/Images.xcassets/logoSignal.imageset/logoSignal.pdf
>    <https://github.com/WhisperSystems/Signal-iOS/pull/517/files#diff-7>
>    (0)
>    - *A* Signal/Images.xcassets/uiEmpty.imageset/Contents.json
>    <https://github.com/WhisperSystems/Signal-iOS/pull/517/files#diff-8>
>    (12)
>    - *A* Signal/Images.xcassets/uiEmpty.imageset/uiEmpty.pdf
>    <https://github.com/WhisperSystems/Signal-iOS/pull/517/files#diff-9>
>    (0)
>    - *A* Signal/Images.xcassets/uiEmptyArchive.imageset/Contents.json
>    <https://github.com/WhisperSystems/Signal-iOS/pull/517/files#diff-10>
>    (12)
>    - *A* Signal/Images.xcassets/uiEmptyArchive.imageset/uiEmptyArchive.pdf
>    <https://github.com/WhisperSystems/Signal-iOS/pull/517/files#diff-11>
>    (0)
>    - *A* Signal/Images.xcassets/uiEmptyContact.imageset/Contents.json
>    <https://github.com/WhisperSystems/Signal-iOS/pull/517/files#diff-12>
>    (12)
>    - *A* Signal/Images.xcassets/uiEmptyContact.imageset/uiEmptyContact.pdf
>    <https://github.com/WhisperSystems/Signal-iOS/pull/517/files#diff-13>
>    (0)
>    - *A* Signal/Images.xcassets/uiEmptyInbox.imageset/Contents.json
>    <https://github.com/WhisperSystems/Signal-iOS/pull/517/files#diff-14>
>    (12)
>    - *A* Signal/Images.xcassets/uiEmptyInbox.imageset/uiEmptyInbox.pdf
>    <https://github.com/WhisperSystems/Signal-iOS/pull/517/files#diff-15>
>    (0)
>
> Patch Links:
>
>    - https://github.com/WhisperSystems/Signal-iOS/pull/517.patch
>    - https://github.com/WhisperSystems/Signal-iOS/pull/517.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/pull/517>.
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by FredericJacobs** [comment]
You can merge those to commits to your branch, I will merge them when you're doing a PR, sounds good?

**Comment by corbett** [comment]
I don't like that flow. I really like having separate things to review.
when you do that it makes it really hard for me to try to find what to
review. I can do it to you, but it also makes me worried that you'll miss
potential issues in a sea of design stuff.

c

On Mon, Jan 26, 2015 at 4:23 PM, Frederic Jacobs <notifications@github.com>
wrote:

> You can merge those to commits to your branch, I will merge them when
> you're doing a PR, sounds good?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/pull/517#issuecomment-71579310>
> .
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by FredericJacobs** [comment]
Well, I thought that your PR would be integrating those ressources.
You would still make distinct commits so it's not too hard too review.

**Comment by FredericJacobs** [comment]
Merging this with @corbett's PR. Thanks @helveticade!

**Pull request closed without merging**
