### PR TITLE
Support for various screen sizes.

### PR DESCRIPTION
**Pull request by FredericJacobs**

### CODE REVIEW

**Comment by corbett** [comment]
this was tested on 5, 6 and 6+ as well?

**Comment by FredericJacobs** [comment]
4S (Simulator), 5, 6 (Simulator), 6+

**Comment by corbett** [comment]
want to try on device onthe 6?

**Comment by FredericJacobs** [comment]
I think we're good. If you happen to be able to test it on device, then fine but I wouldn't request code signing certs and stuff just for this.

**Comment by corbett** [comment]
cool..

On Fri, Jan 30, 2015 at 5:42 PM, Frederic Jacobs <notifications@github.com>
wrote:

> I think we're good. If you happen to be able to test it on device, then
> fine but I wouldn't request code signing certs and stuff just for this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/pull/548#issuecomment-72302899>
> .
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by FredericJacobs** [comment]
Merged

**Pull request closed without merging**
