### PR TITLE
Refactoring conditional directives that split up parts of statements.

### PR DESCRIPTION
**Pull request by flaviommedeiros**
A suggestion to compile entire statements and expressions, as suggested by code style guidelines from the Linux Kernel and practitioners.

- https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle#n892
- https://www.cqse.eu/en/blog/living-in-the-ifdef-hell/

It might improve code understanding, maintainability and error-proneness.

### CODE REVIEW

**Comment by haffenloher** [comment]
I don't think it's useful to start making code style fixes to third-party library code.

**Comment by FredericJacobs** [comment]
What @haffenloher said

**Comment by RomeroMalaquias** [comment]
Hello @haffenloher and @FredericJacobs   i'm from the same research team of flaviommedeiros and i need to ask if you prefer this code before or after the commit. What do you think about this kind of change? 
Thanks in advance.

**Comment by RomeroMalaquias** [comment]
I mean, would you accept if it was not for the fact we submitted the pull request to a code written by third parties?

**Comment by michaelkirk** [comment]
The proposal *is* good style, but it's unlikely we'll accept code-style changes which aren't fixing a user facing bug or adding a feature, as it opens the door to too many well intentioned changes that could break something.

**Pull request closed without merging**
