### PR TITLE
treat sending to ourselves in a single thread, as on Android

### PR DESCRIPTION
**Pull request by corbett**

### CODE REVIEW

**Comment by FredericJacobs** [comment]
Can you also add support for calling yourself? Right now it crashes when I try to call myself.

**Comment by corbett** [comment]
sure I would do that on a separate PR though, could you make a separate
issue for that

On Sun, Jan 11, 2015 at 2:06 AM, Frederic Jacobs <notifications@github.com>
wrote:

> Can you also add support for calling yourself? Right now it crashes when I
> try to call myself.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/pull/305#issuecomment-69480560>
> .
>



-- 
Dr. Corbett Moran
Rockets @ http://www.spacex.com
Physics @ http://www.ICS.uzh.ch  <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Comment by corbett** [comment]
@FredericJacobs I don't think RedPhone should support calling yourself. I'll disable that. But separate PR/issue #314

**Comment by corbett** [comment]
OK... so giving this a little thought, I disabled this behavior on the UI level the PR is updated. you can't call yourself. 
-in a thread with yourself, the call button is not available
-if you try to dial yourself in the dialer it won't let you with a message indicating why

**Comment by corbett** [comment]
@FredericJacobs if you close a PR could you remove the "in review" label too?

**Comment by FredericJacobs** [comment]
Will do

**Pull request closed without merging**
