### PR TITLE
Fixes Call Error message text should adapt size... (#1164)

### PR DESCRIPTION
**Pull request by big-r81**
### First time contributor checklist

- [x] I have read the [README](https://github.com/WhisperSystems/Signal-iOS/blob/master/README.md) and [CONTRIBUTING](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md) documents
- [x] I have signed the [Contributor Licence Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I'm following the [code, UI and style conventions](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md#code-conventions)
- [x] My commits are rebased on the latest master branch
- [x] My commits are in nice logical chunks
- [x] My contribution is fully baked and is ready to be merged as is
- [x] I have tested my contribution on these devices:
 * iPhone 6, iOS 9.3.1
- [x] I have made the choice whether I want the [BitHub reward](https://github.com/WhisperSystems/Signal-Android/wiki/BitHub-Rewards) or not by omitting or adding the word `FREEBIE` in my commit message

- - - - - - - - - -

### Description

Fixes Call Error message text should adapt size to fit localized text  (#1164)

- adding constraints and changing properties for _callStatusLabel to
fit 3 lines of text

//FREEBIE

### CODE REVIEW

**Comment by big-r81** [comment]
damn, i forgot it...
i will correct this!

**Comment by haffenloher** [comment]
Huh I'm sorry, there's no need to close your PR! Amending your commit msg and force-pushing should do the trick

**Comment by big-r81** [comment]
okay, i have amended my commit messag and pushed again my branch to my repository...
Ho can i now repush to this PR or is it to late and i have to do a new PR?

**Comment by michaelkirk** [comment]
I think if you reopen it, GH will update.

**Comment by big-r81** [comment]
okay in my repo the commit is updated, but not here...

**Comment by big-r81** [comment]
I cant reopen this PR, so i will make a new one...

**Pull request closed without merging**
