### PR TITLE
Conversations

### PR DESCRIPTION
**Pull request by corbett**
Conversations view issues from 98 issues. Looks fairly ugly, icon sizes will need tweaked to Tyler's taste and the new messages count label probably should disappear or change colors from blue when the blue inbox is selected.

### CODE REVIEW

**Comment by FredericJacobs** [comment]
The new settings icon was already ticked off and part of the `Design-Tyler...` branch

**Comment by corbett** [comment]
oh OK, um should I be branching/PRing off that? you didn't mention that on our call. just remove that commit then.

**Comment by FredericJacobs** [comment]
I'll drop that commit when merging. You can base your next PRs on the `Design-Tyler...` branch so that you see the result in context with the other iconography that was changed.

**Comment by corbett** [comment]
ok

On Sun, Feb 15, 2015 at 6:37 PM, Frederic Jacobs <notifications@github.com>
wrote:

> I'll drop that commit when merging. You can base your next PRs on the
> Design-Tyler... branch so that you see the result in context with the
> other iconography that was changed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-iOS/pull/596#issuecomment-74430075>
> .
>



-- 
Dr. Corbett Moran
Physics @ http://www.tapir.caltech.edu <http://www.ICS.uzh.ch>
Dev @ http://circleof6app.com
Dev @ https://whispersystems.org
www.christinecorbettmoran.com

**Pull request closed without merging**
