### PR TITLE
Design improvements

### PR DESCRIPTION
**Pull request by corbett**

### CODE REVIEW

**Comment by FredericJacobs** [comment]
Hey,
I emailed you a screenshot from the app showing some issues with the alignement of the phones on the 6+.

**Comment by corbett** [comment]
The phone issue was fixed in a separate PR that I got out earlier I didn't rebase on it

**Comment by FredericJacobs** [comment]
Got it, I did a mistake in fixing a conflict in Storyboard. Fixed now.

**Comment by FredericJacobs** [comment]
I have an issue with the New Message screen placeholder because it's prevents to do a pull to refresh.

**Comment by FredericJacobs** [comment]
Merged but refresh on New Message view needs to be addressed.

**Pull request closed without merging**
