### PR TITLE
Show alert when attempting to take photo after disabling camera permi…

### PR DESCRIPTION
**Pull request by jaropawlak**
### First time contributor checklist

- [x] I have read the [README](https://github.com/WhisperSystems/Signal-iOS/blob/master/README.md) and [CONTRIBUTING](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md) documents
- [x] I have signed the [Contributor Licence Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I'm following the [code, UI and style conventions](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md#code-conventions)
- [x] My commits are rebased on the latest master branch
- [x] My commits are in nice logical chunks
- [x] My contribution is fully baked and is ready to be merged as is
- [x] I have tested my contribution on these devices:
 *iPhone 5, iOS 10
- [x] I have made the choice whether I want the [BitHub reward](https://github.com/WhisperSystems/Signal-Android/wiki/BitHub-Rewards) or not by omitting or adding the word `FREEBIE` in my commit message

- - - - - - - - - -

### CODE REVIEW

**Comment by michaelkirk** [comment]
Hrm. Well...

From CONTRIBUTING.md
> Please go ahead and sign, putting your github username in "Address line #2", so that we can accept your pull requests at our heart's delight.

Just double checking, you did that right?

**Comment by jaropawlak** [comment]
I did with the very first pull request. I can try again.

**Comment by jaropawlak** [comment]
I did again, I got redirected to github and I got "thank you for agreement".

**Comment by michaelkirk** [comment]
> what should I do with cla-server/validation? Should I fill the form again?

I have very little confidence it work at this point. 

Could you send a screenshot of your filled out form to michael@whispersystems.org, and we'll call it good?

E.g. 
screen shot 2016-10-04 at 2 29 54 pm

**Comment by jaropawlak** [comment]
ok. I sent you a mail.

**Comment by jaropawlak** [comment]
are we good to go?

**Comment by michaelkirk** [comment]
Everything looks good from my end.

I’m going to wait until the 2.6.0 release before merging several pull requests, so we can keep a more linear release and commit history.

**Comment by michaelkirk** [comment]
Hey thanks for your patience. This will be a helpful feature, but I think we can be more helpful to the user.

Title: "Signal Would Like to Access to Your Camera"
Body: "You need to go to your settings and allow Signal access to your camera in order to proceed.";
Cancel Action: "Dismiss"
Default Action: "Open Settings"

see: http://stackoverflow.com/questions/5655674/opening-the-settings-app-from-another-app

We also use the camera to scan QR codes when linking devices and verifying safety numbers. You'll get bonus points if you can extract this behavior into something reusable for those other two scenarios, but if not, getting it here would be a great start.

**Comment by jaropawlak** [comment]
ok, I'll handle both scenarios. I thought also about first opening of camera (right after install). If you deny permissions on first access - it shows camera screen without camera. I'd like to correct that too.

**Pull request closed without merging**
