### PR TITLE
Disable the "scroll to new message" animation.

### PR DESCRIPTION
**Pull request by charlesmchen**
PTAL @michaelkirk

### CODE REVIEW

**Comment by michaelkirk** [comment]
Although as is, it is annoying, we haven't yet implemented another indication of new messages received while scrolling back in a thread.

**Comment by charlesmchen** [comment]
> Although as is, it is annoying, we haven't yet implemented another indication of new messages received while scrolling back in a thread.

Sorry if this wasn't clear.  This doesn't affect the behavior when we receive new _incoming_ messages. This affects the behavior when we send a new _outgoing_ message. Per Moxie in standup, it feels snappier to skip the "new outgoing message rolls onscreen" message. Note that we auto-scroll to the bottom of the conversation whenever user activates the new message text field, so users should usually be at the bottom when this happens. They could add a message, scroll up, and hit "send", in which case the app should still animate to the new message. I'll check that last case.

**Comment by michaelkirk** [comment]
> This doesn't affect the behavior when we receive new incoming messages. 

Huh. it sure looks like it would. `scrollToBottom` is set to `YES` whenever we're inserting a row, which would be either incoming or outgoing. What am I missing?

**Comment by charlesmchen** [comment]
> Huh. it sure looks like it would. scrollToBottom is set to YES whenever we're inserting a row, which would be either incoming or outgoing. What am I missing?

You're right. PTAL

**Comment by charlesmchen** [comment]
@michaelkirk There's more work to be done on this task. I'll do it in a subsequent PR.

**Pull request merged**
