### PR TITLE
Switch back to the default keyboard after sending

### PR DESCRIPTION
**Pull request by jschneier**
### First time contributor checklist

- [x] I have read the [README](https://github.com/WhisperSystems/Signal-iOS/blob/master/README.md) and [CONTRIBUTING](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md) documents
- [x] I have signed the [Contributor Licence Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I'm following the [code, UI and style conventions](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md#code-conventions)
- [x] My commits are rebased on the latest master branch
- [x] My commits are in nice logical chunks
- [x] My contribution is fully baked and is ready to be merged as is
- [x] I have tested my contribution on these devices:
 * iPhone SE, iOS 9.3.5
- [x] I have made the choice whether I want the [BitHub reward](https://github.com/WhisperSystems/Signal-Android/wiki/BitHub-Rewards) or not by omitting or adding the word `FREEBIE` in my commit message

- - - - - - - - - -

### Description

This is behavior that I am expecting that is builtin to the default Messages app as well as Whatsapp. I tried experimenting with `UIKeyboardType` but that is a red herring. I tested with a non-US keyboard (Arabic).

These gifs are pre and post patch respectively. My apologies for the speed. It turns out converting mov files to gifs and getting a nice balance of speed and optimization is quite an annoying process.

Let me know if there is anything else you need from me!

nopatch
patched

### CODE REVIEW

**Comment by jschneier** [comment]
@michaelkirk should i have opened an issue first? sorry!

**Comment by michaelkirk** [comment]
> @michaelkirk should i have opened an issue first? sorry!

No issue necessary if there's already a PR open.

**Comment by michaelkirk** [comment]
Hi @jschneier, thanks for working on this, it's a good feature.

However, the current implementation, which dismisses and re-pops the keyboard in succession causes a weird animation after every sent message.

This might offer a better solution: https://github.com/jessesquires/JSQMessagesViewController/issues/971

**Comment by jschneier** [comment]
@michaelkirk interesting, I didn't see that animation on my test device. I see that at some point we unforked JSQMessagesViewController! Awesome. Let me get the code wrapped in the fix in that thread and then I will ping you later today when I update the PR.

**Comment by jschneier** [comment]
@michaelkirk I updated as guided and also managed to figure out how to replicate the behavior with regards to the emoji keyboard. Tricky to track down.

Let me know if you have any other concerns!

**Comment by michaelkirk** [comment]
This is working well for me now. Thanks for the fix. 


One finaly nit, for the future peeps, can you leave a comment in the code as to why we're doing this? Or wrap it in a self descriptive method like `toggleDefaultKeyboard`.

**Comment by jschneier** [comment]
@michaelkirk done, went for the method.

**Pull request merged**
