### PR TITLE
respect system sort order for contacts

### PR DESCRIPTION
**Pull request by michaelkirk**
Fixes https://github.com/WhisperSystems/Signal-iOS/issues/2154

### CODE REVIEW

**Comment by charlesmchen** [comment]
So, the question is where should we honor this?

* "new 1:1 conversation view" seems like an obvious yes.
* The group views are more ambiguous since they could be a mix of contacts and non-contacts.
*  The Block list view is likely to be mostly non-contacts.

Also, via profiles we'll soon have more "display names", and our profile names don't have separate first/last components.  It'd be weird if we showed a mixture of phone numbers, contact names, profile names with inconsistent sorting between them.

**Comment by charlesmchen** [comment]
In lots of the views (like the group views) we sort by recipient id right now FYI.

**Comment by michaelkirk** [comment]
> So, the question is where should we honor this?
> 
> "new 1:1 conversation view" seems like an obvious yes.
> The group views are more ambiguous since they could be a mix of contacts and non-contacts.
> The Block list view is likely to be mostly non-contacts.
> Also, via profiles we'll soon have more "display names", and our profile names don't have separate > first/last components. It'd be weird if we showed a mixture of phone numbers, contact names, profile names with inconsistent sorting between them.

This PR fixes sorting the results returned by the contactFetcher. So anything that respects that sort order (anything using `contactsHelper.allContacts`) benefits from this.

for example:
- picking contact when starting new 1:1 conversation
- selecting contacts when creating a new group
- adding a contact to group
- blocking a contact

Since it seems like all forward movement (which I think covers 99% of the common use case). Are you OK with merging this as is, and building it out as necessary for future feature work?

**Comment by charlesmchen** [comment]
> Since it seems like all forward movement (which I think covers 99% of the common use case). Are you OK with merging this as is, and building it out as necessary for future feature work?

Totally - just wanted to remember that we might not get this for free everywhere.  We should also make sure that we're still honoring sort order when searching, for example.

**Comment by charlesmchen** [comment]
And I do think there are some difficult questions about consistency is certain places.

**Comment by michaelkirk** [comment]
thanks for the feedback.

Rebased and merged in: https://github.com/WhisperSystems/Signal-iOS/commit/3162160b5ef55522f6bf92cd381139ec091d5534

**Pull request closed without merging**
